server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 1. เอา / ออกจากท้าย location
    location /api/auth {
        # 2. เอา / ออกจากท้าย URL เพื่อให้มันส่ง Path ไปเต็มๆ (/api/auth/login)
        proxy_pass http://auth-service-production-23d0.up.railway.app; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_redirect off;
    }
}